CREATE DATABASE LIBRARYSITH;
USE LIBRARYSITH;

CREATE TABLE AUTHOR(

ID      INTEGER AUTO_INCREMENT,
NAME_   VARCHAR(40),
BIRTH   DATE,
PRIMARY KEY(ID)
);

INSERT INTO AUTHOR (NAME_, BIRTH) VALUES ("Marka Ragnos", "1560-01-03");
INSERT INTO AUTHOR (NAME_, BIRTH) VALUES ("Dathka Graush", "1720-05-02");
INSERT INTO AUTHOR (NAME_, BIRTH) VALUES ("Naga Sadow", "1800-12-06");