CREATE DATABASE LIBRARYSITH;
USE LIBRARYSITH;

CREATE TABLE AUTHOR(

    ID      INTEGER AUTO_INCREMENT,
    NAME_   VARCHAR(40),
    BIRTH   DATE,
    PRIMARY KEY(ID)
);

CREATE TABLE BOOK(

     ID INTEGER AUTO_INCREMENT,
     TITLE VARCHAR(50),
     EDITION VARCHAR(50),
     PRIMARY KEY(ID),
     AUTHOR_ID INTEGER,
     FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(ID)
);

INSERT INTO AUTHOR (NAME_, BIRTH) VALUES ("Marka Ragnos", "1560-01-03");
INSERT INTO AUTHOR (NAME_, BIRTH) VALUES ("Dathka Graush", "1720-05-02");
INSERT INTO AUTHOR (NAME_, BIRTH) VALUES ("Naga Sadow", "1800-12-06");

INSERT INTO BOOK (TITLE, EDITION, AUTHOR_ID) VALUES ("The Golden Age of the Sith", "3rd edition", 3);
INSERT INTO BOOK (TITLE, EDITION, AUTHOR_ID) VALUES ("Jedi Academy", "1st edition", 1);
INSERT INTO BOOK (TITLE, EDITION, AUTHOR_ID) VALUES ("The Fall  the Sith Empire", "2nd ofedition", 3);